INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('The Golden Fork', '12 High Street', 'Springfield', 'SP1 4RT');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Blue Ocean Bistro', '45 Seaview Avenue', 'Brighton', 'BN2 7LH');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Red Lantern Bar', '8 Market Square', 'Cambridge', 'CB1 2QZ');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('The Green Vine', '21 Vineyard Road', 'Winchester', 'SO23 9JD');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Rustic Barrel Pub', '34 Main Street', 'York', 'YO1 8HD');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Citrus Grove Café', '10 Orchard Lane', 'Manchester', 'M4 5BQ');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('The Velvet Spoon', '3 Castle Road', 'Edinburgh', 'EH1 2AD');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Midnight Espresso', '7 King’s Lane', 'Bath', 'BA1 1AB');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Olive & Thyme', '19 Riverside Walk', 'Durham', 'DH1 3LT');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('The Laughing Pint', '14 Station Road', 'Leeds', 'LS1 2JP');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Amber Ale House', '50 Brewery Street', 'Birmingham', 'B1 3LR');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Cherry Blossom Sushi', '6 Bridge Street', 'Oxford', 'OX1 4BT');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Smoky Barrel BBQ', '22 West Avenue', 'Bristol', 'BS1 5AL');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('The Scarlet Flame', '11 Crescent Road', 'Cardiff', 'CF10 3AD');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Golden Harvest Diner', '9 Farmer’s Way', 'Norwich', 'NR1 4ET');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Steakhouse on the Hill', '25 Summit Lane', 'Sheffield', 'S1 4BG');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('The Copper Kettle', '5 Victoria Street', 'Nottingham', 'NG1 2FH');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Urban Grill & Lounge', '30 City Center Plaza', 'London', 'WC1E 6HG');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('Neon Nights Bar', '40 Electric Avenue', 'Liverpool', 'L1 8JT');
INSERT INTO customers (name, addressLine1, town, postcode) VALUES ('The Roasted Bean', '17 Market Road', 'Chester', 'CH1 2AB');

INSERT INTO products (name, description) VALUES ('Golden Ale', 'A smooth, malty ale with a hint of citrus and a golden amber hue.');
INSERT INTO products (name, description) VALUES ('Midnight Stout', 'A dark, creamy stout with rich coffee and chocolate notes.');
INSERT INTO products (name, description) VALUES ('Crisp Lager', 'A refreshing, light lager with a clean finish and subtle hop aroma.');
INSERT INTO products (name, description) VALUES ('Ruby Red IPA', 'A bold IPA with a robust malt backbone and fruity hop character.');
INSERT INTO products (name, description) VALUES ('Honey Wheat Beer', 'A light, slightly sweet wheat beer brewed with real honey.');
INSERT INTO products (name, description) VALUES ('Spiced Winter Ale', 'A seasonal ale with warm spices, hints of cinnamon and nutmeg.');
INSERT INTO products (name, description) VALUES ('Cider Orchard Bliss', 'A crisp, refreshing cider made with hand-picked apples.');
INSERT INTO products (name, description) VALUES ('Tropical Hazy IPA', 'A juicy, hazy IPA bursting with tropical fruit flavors.');
INSERT INTO products (name, description) VALUES ('Smoky Porter', 'A robust porter with deep smoky undertones and a smooth finish.');
INSERT INTO products (name, description) VALUES ('Barrel-Aged Bourbon Ale', 'A rich ale aged in bourbon barrels for caramel and oak notes.');
INSERT INTO products (name, description) VALUES ('Pomegranate Sour', 'A tart, tangy sour beer with a burst of pomegranate flavor.');
INSERT INTO products (name, description) VALUES ('Classic Pilsner', 'A crisp, clean pilsner with a delicate balance of hops and malt.');
INSERT INTO products (name, description) VALUES ('Cherry Wheat', 'A refreshing wheat beer with a touch of sweet cherry flavor.');
INSERT INTO products (name, description) VALUES ('Dark Rum Reserve', 'A rich, full-bodied dark rum with caramel and vanilla notes.');
INSERT INTO products (name, description) VALUES ('Premium Gin', 'A smooth gin infused with botanicals, citrus, and a hint of juniper.');
INSERT INTO products (name, description) VALUES ('Small Batch Whiskey', 'An artisanal whiskey with notes of oak, caramel, and spice.');
INSERT INTO products (name, description) VALUES ('Craft Vodka', 'A clean, crisp vodka distilled for exceptional smoothness.');
INSERT INTO products (name, description) VALUES ('Rosé Spritzer', 'A light and bubbly spritzer with delicate rosé wine notes.');
INSERT INTO products (name, description) VALUES ('Peach Mead', 'A sweet, golden mead brewed with ripe peaches and floral honey.');
INSERT INTO products (name, description) VALUES ('Classic Margarita Mix', 'A zesty mix of lime, orange, and tequila for the perfect cocktail.');

INSERT INTO orders (name, customerId) VALUES ('Valentine''s Day Special Menu', 1);
INSERT INTO orders (name, customerId) VALUES ('Christmas Wine List', 2);
INSERT INTO orders (name, customerId) VALUES ('Summer Cocktail Selection', 3);
INSERT INTO orders (name, customerId) VALUES ('Oktoberfest Beer Menu', 4);
INSERT INTO orders (name, customerId) VALUES ('New Year''s Eve Celebration Drinks', 5);
INSERT INTO orders (name, customerId) VALUES ('Spring Seasonal Specials', 6);
INSERT INTO orders (name, customerId) VALUES ('Autumn Craft Beers', 7);
INSERT INTO orders (name, customerId) VALUES ('Chef''s Tasting Menu', 8);
INSERT INTO orders (name, customerId) VALUES ('Winter Warmers Drinks List', 9);
INSERT INTO orders (name, customerId) VALUES ('Tropical Drinks Showcase', 10);
